version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Belgrade"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:15"
      timezone: "Europe/Belgrade"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Europe/Belgrade"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:45"
      timezone: "Europe/Belgrade"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
