version: 2

project_name: nebula-mnemosina

before:
  hooks:
    - go mod tidy
    - sqlc generate

builds:
  - id: nebula-mnemosina
    main: ./cmd/nebula-mnemosina
    binary: nebula-mnemosina
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .Commit }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

dockers:
  - id: linux-amd64
    ids:
      - nebula-mnemosina
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - ghcr.io/vooon/nebula-mnemosina:{{ .Tag }}-amd64
    build_flag_templates:
      - --platform=linux/amd64
  - id: linux-arm64
    ids:
      - nebula-mnemosina
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - ghcr.io/vooon/nebula-mnemosina:{{ .Tag }}-arm64
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: ghcr.io/vooon/nebula-mnemosina:{{ .Tag }}
    image_templates:
      - ghcr.io/vooon/nebula-mnemosina:{{ .Tag }}-amd64
      - ghcr.io/vooon/nebula-mnemosina:{{ .Tag }}-arm64
  - name_template: ghcr.io/vooon/nebula-mnemosina:latest
    image_templates:
      - ghcr.io/vooon/nebula-mnemosina:{{ .Tag }}-amd64
      - ghcr.io/vooon/nebula-mnemosina:{{ .Tag }}-arm64
