FROM scratch

COPY nebula-mnemosina /usr/local/bin/nebula-mnemosina
COPY --chown=65532:65532 docker/rootfs/data /data

USER 65532:65532
VOLUME ["/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/nebula-mnemosina"]
