// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HostmapEntry struct {
	ID                     pgtype.Int8        `json:"id"`
	PollRunID              int64              `json:"poll_run_id"`
	ObservedAt             pgtype.Timestamptz `json:"observed_at"`
	LighthouseName         string             `json:"lighthouse_name"`
	Source                 string             `json:"source"`
	EntryIndex             int32              `json:"entry_index"`
	VpnAddrs               []string           `json:"vpn_addrs"`
	PrimaryVpnAddr         pgtype.Text        `json:"primary_vpn_addr"`
	LocalIndex             int64              `json:"local_index"`
	RemoteIndex            int64              `json:"remote_index"`
	RemoteAddrs            []string           `json:"remote_addrs"`
	MessageCounter         int64              `json:"message_counter"`
	CurrentRemote          string             `json:"current_remote"`
	CurrentRelaysToMe      []string           `json:"current_relays_to_me"`
	CurrentRelaysThroughMe []string           `json:"current_relays_through_me"`
	CertCurve              pgtype.Text        `json:"cert_curve"`
	CertName               pgtype.Text        `json:"cert_name"`
	CertFingerprint        pgtype.Text        `json:"cert_fingerprint"`
	CertPublicKey          pgtype.Text        `json:"cert_public_key"`
	CertSignature          pgtype.Text        `json:"cert_signature"`
	CertVersion            pgtype.Int4        `json:"cert_version"`
	CertGroups             []string           `json:"cert_groups"`
	CertIsCa               pgtype.Bool        `json:"cert_is_ca"`
	CertIssuer             pgtype.Text        `json:"cert_issuer"`
	CertNetworks           []string           `json:"cert_networks"`
	CertUnsafeNetworks     []string           `json:"cert_unsafe_networks"`
	CertNotBefore          pgtype.Timestamptz `json:"cert_not_before"`
	CertNotAfter           pgtype.Timestamptz `json:"cert_not_after"`
	Raw                    []byte             `json:"raw"`
}

type LighthouseAddrmapEntry struct {
	ID              pgtype.Int8        `json:"id"`
	PollRunID       int64              `json:"poll_run_id"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	LighthouseName  string             `json:"lighthouse_name"`
	VpnAddr         string             `json:"vpn_addr"`
	ReporterVpnAddr pgtype.Text        `json:"reporter_vpn_addr"`
	LearnedAddrs    []string           `json:"learned_addrs"`
	ReportedAddrs   []string           `json:"reported_addrs"`
	RelayVpnAddrs   []string           `json:"relay_vpn_addrs"`
	Raw             []byte             `json:"raw"`
}

type MnemoCurrentLighthouseAddrmap struct {
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	LighthouseName  string             `json:"lighthouse_name"`
	VpnAddr         string             `json:"vpn_addr"`
	ReporterVpnAddr pgtype.Text        `json:"reporter_vpn_addr"`
	LearnedAddrs    []string           `json:"learned_addrs"`
	ReportedAddrs   []string           `json:"reported_addrs"`
	RelayVpnAddrs   []string           `json:"relay_vpn_addrs"`
}

type MnemoCurrentPeer struct {
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	LighthouseName     string             `json:"lighthouse_name"`
	PeerKey            pgtype.Text        `json:"peer_key"`
	PrimaryVpnAddr     pgtype.Text        `json:"primary_vpn_addr"`
	VpnAddrs           []string           `json:"vpn_addrs"`
	CertName           pgtype.Text        `json:"cert_name"`
	CertFingerprint    pgtype.Text        `json:"cert_fingerprint"`
	CertGroups         []string           `json:"cert_groups"`
	CertNetworks       []string           `json:"cert_networks"`
	CertUnsafeNetworks []string           `json:"cert_unsafe_networks"`
	CertNotBefore      pgtype.Timestamptz `json:"cert_not_before"`
	CertNotAfter       pgtype.Timestamptz `json:"cert_not_after"`
	CurrentRemote      string             `json:"current_remote"`
	RemoteAddrs        []string           `json:"remote_addrs"`
	MessageCounter     int64              `json:"message_counter"`
	LocalIndex         int64              `json:"local_index"`
	RemoteIndex        int64              `json:"remote_index"`
	NebulaVersion      pgtype.Text        `json:"nebula_version"`
}

type MnemoLighthouseDisagreement struct {
	VpnAddr              string      `json:"vpn_addr"`
	LighthousesReporting int64       `json:"lighthouses_reporting"`
	DistinctLearnedSets  int64       `json:"distinct_learned_sets"`
	LearnedByLighthouse  interface{} `json:"learned_by_lighthouse"`
	LatestObservedAt     interface{} `json:"latest_observed_at"`
}

type MnemoPeerCertInventory struct {
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	PeerKey            pgtype.Text        `json:"peer_key"`
	PrimaryVpnAddr     pgtype.Text        `json:"primary_vpn_addr"`
	VpnAddrs           []string           `json:"vpn_addrs"`
	CertName           pgtype.Text        `json:"cert_name"`
	CertFingerprint    pgtype.Text        `json:"cert_fingerprint"`
	CertPublicKey      pgtype.Text        `json:"cert_public_key"`
	CertGroups         []string           `json:"cert_groups"`
	CertNetworks       []string           `json:"cert_networks"`
	CertUnsafeNetworks []string           `json:"cert_unsafe_networks"`
	CertNotBefore      pgtype.Timestamptz `json:"cert_not_before"`
	CertNotAfter       pgtype.Timestamptz `json:"cert_not_after"`
}

type MnemoPollHealth5m struct {
	Bucket          interface{} `json:"bucket"`
	LighthouseName  string      `json:"lighthouse_name"`
	Polls           int64       `json:"polls"`
	SuccessfulPolls int64       `json:"successful_polls"`
	FailedPolls     int64       `json:"failed_polls"`
	P95DurationMs   float64     `json:"p95_duration_ms"`
	LatestPollAt    interface{} `json:"latest_poll_at"`
}

type PollRun struct {
	ID             int64              `json:"id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	LighthouseName string             `json:"lighthouse_name"`
	SshTarget      string             `json:"ssh_target"`
	Success        bool               `json:"success"`
	DurationMs     int64              `json:"duration_ms"`
	Error          pgtype.Text        `json:"error"`
	NebulaVersion  pgtype.Text        `json:"nebula_version"`
	DeviceName     pgtype.Text        `json:"device_name"`
	DeviceCidrs    []string           `json:"device_cidrs"`
	CommandCount   int32              `json:"command_count"`
}

type RawCommandPayload struct {
	ID             int64              `json:"id"`
	PollRunID      int64              `json:"poll_run_id"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
	LighthouseName string             `json:"lighthouse_name"`
	Command        string             `json:"command"`
	Success        bool               `json:"success"`
	DurationMs     int64              `json:"duration_ms"`
	Output         string             `json:"output"`
	Error          pgtype.Text        `json:"error"`
}

type RelaySnapshot struct {
	ID             pgtype.Int8        `json:"id"`
	PollRunID      int64              `json:"poll_run_id"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
	LighthouseName string             `json:"lighthouse_name"`
	Relays         []byte             `json:"relays"`
}

type SchemaMigration struct {
	Version   string             `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}
