// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: poll_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completePollRun = `-- name: CompletePollRun :exec
UPDATE poll_runs
SET
    finished_at = $2,
    success = $3,
    duration_ms = $4,
    error = $5,
    nebula_version = $6,
    device_name = $7,
    device_cidrs = $8,
    command_count = $9
WHERE id = $1
`

type CompletePollRunParams struct {
	ID            int64              `json:"id"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Success       bool               `json:"success"`
	DurationMs    int64              `json:"duration_ms"`
	Error         pgtype.Text        `json:"error"`
	NebulaVersion pgtype.Text        `json:"nebula_version"`
	DeviceName    pgtype.Text        `json:"device_name"`
	DeviceCidrs   []string           `json:"device_cidrs"`
	CommandCount  int32              `json:"command_count"`
}

func (q *Queries) CompletePollRun(ctx context.Context, arg CompletePollRunParams) error {
	_, err := q.db.Exec(ctx, completePollRun,
		arg.ID,
		arg.FinishedAt,
		arg.Success,
		arg.DurationMs,
		arg.Error,
		arg.NebulaVersion,
		arg.DeviceName,
		arg.DeviceCidrs,
		arg.CommandCount,
	)
	return err
}

const createPollRun = `-- name: CreatePollRun :one
INSERT INTO poll_runs (
    started_at,
    lighthouse_name,
    ssh_target
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreatePollRunParams struct {
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	LighthouseName string             `json:"lighthouse_name"`
	SshTarget      string             `json:"ssh_target"`
}

func (q *Queries) CreatePollRun(ctx context.Context, arg CreatePollRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPollRun, arg.StartedAt, arg.LighthouseName, arg.SshTarget)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertHostmapEntry = `-- name: InsertHostmapEntry :exec
INSERT INTO hostmap_entries (
    poll_run_id,
    observed_at,
    lighthouse_name,
    source,
    entry_index,
    vpn_addrs,
    primary_vpn_addr,
    local_index,
    remote_index,
    remote_addrs,
    message_counter,
    current_remote,
    current_relays_to_me,
    current_relays_through_me,
    cert_curve,
    cert_name,
    cert_fingerprint,
    cert_public_key,
    cert_signature,
    cert_version,
    cert_groups,
    cert_is_ca,
    cert_issuer,
    cert_networks,
    cert_unsafe_networks,
    cert_not_before,
    cert_not_after,
    raw
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28
)
`

type InsertHostmapEntryParams struct {
	PollRunID              int64              `json:"poll_run_id"`
	ObservedAt             pgtype.Timestamptz `json:"observed_at"`
	LighthouseName         string             `json:"lighthouse_name"`
	Source                 string             `json:"source"`
	EntryIndex             int32              `json:"entry_index"`
	VpnAddrs               []string           `json:"vpn_addrs"`
	PrimaryVpnAddr         pgtype.Text        `json:"primary_vpn_addr"`
	LocalIndex             int64              `json:"local_index"`
	RemoteIndex            int64              `json:"remote_index"`
	RemoteAddrs            []string           `json:"remote_addrs"`
	MessageCounter         int64              `json:"message_counter"`
	CurrentRemote          string             `json:"current_remote"`
	CurrentRelaysToMe      []string           `json:"current_relays_to_me"`
	CurrentRelaysThroughMe []string           `json:"current_relays_through_me"`
	CertCurve              pgtype.Text        `json:"cert_curve"`
	CertName               pgtype.Text        `json:"cert_name"`
	CertFingerprint        pgtype.Text        `json:"cert_fingerprint"`
	CertPublicKey          pgtype.Text        `json:"cert_public_key"`
	CertSignature          pgtype.Text        `json:"cert_signature"`
	CertVersion            pgtype.Int4        `json:"cert_version"`
	CertGroups             []string           `json:"cert_groups"`
	CertIsCa               pgtype.Bool        `json:"cert_is_ca"`
	CertIssuer             pgtype.Text        `json:"cert_issuer"`
	CertNetworks           []string           `json:"cert_networks"`
	CertUnsafeNetworks     []string           `json:"cert_unsafe_networks"`
	CertNotBefore          pgtype.Timestamptz `json:"cert_not_before"`
	CertNotAfter           pgtype.Timestamptz `json:"cert_not_after"`
	Raw                    []byte             `json:"raw"`
}

func (q *Queries) InsertHostmapEntry(ctx context.Context, arg InsertHostmapEntryParams) error {
	_, err := q.db.Exec(ctx, insertHostmapEntry,
		arg.PollRunID,
		arg.ObservedAt,
		arg.LighthouseName,
		arg.Source,
		arg.EntryIndex,
		arg.VpnAddrs,
		arg.PrimaryVpnAddr,
		arg.LocalIndex,
		arg.RemoteIndex,
		arg.RemoteAddrs,
		arg.MessageCounter,
		arg.CurrentRemote,
		arg.CurrentRelaysToMe,
		arg.CurrentRelaysThroughMe,
		arg.CertCurve,
		arg.CertName,
		arg.CertFingerprint,
		arg.CertPublicKey,
		arg.CertSignature,
		arg.CertVersion,
		arg.CertGroups,
		arg.CertIsCa,
		arg.CertIssuer,
		arg.CertNetworks,
		arg.CertUnsafeNetworks,
		arg.CertNotBefore,
		arg.CertNotAfter,
		arg.Raw,
	)
	return err
}

const insertLighthouseAddrmapEntry = `-- name: InsertLighthouseAddrmapEntry :exec
INSERT INTO lighthouse_addrmap_entries (
    poll_run_id,
    observed_at,
    lighthouse_name,
    vpn_addr,
    reporter_vpn_addr,
    learned_addrs,
    reported_addrs,
    relay_vpn_addrs,
    raw
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertLighthouseAddrmapEntryParams struct {
	PollRunID       int64              `json:"poll_run_id"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	LighthouseName  string             `json:"lighthouse_name"`
	VpnAddr         string             `json:"vpn_addr"`
	ReporterVpnAddr pgtype.Text        `json:"reporter_vpn_addr"`
	LearnedAddrs    []string           `json:"learned_addrs"`
	ReportedAddrs   []string           `json:"reported_addrs"`
	RelayVpnAddrs   []string           `json:"relay_vpn_addrs"`
	Raw             []byte             `json:"raw"`
}

func (q *Queries) InsertLighthouseAddrmapEntry(ctx context.Context, arg InsertLighthouseAddrmapEntryParams) error {
	_, err := q.db.Exec(ctx, insertLighthouseAddrmapEntry,
		arg.PollRunID,
		arg.ObservedAt,
		arg.LighthouseName,
		arg.VpnAddr,
		arg.ReporterVpnAddr,
		arg.LearnedAddrs,
		arg.ReportedAddrs,
		arg.RelayVpnAddrs,
		arg.Raw,
	)
	return err
}

const insertRawCommandPayload = `-- name: InsertRawCommandPayload :exec
INSERT INTO raw_command_payloads (
    poll_run_id,
    observed_at,
    lighthouse_name,
    command,
    success,
    duration_ms,
    output,
    error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertRawCommandPayloadParams struct {
	PollRunID      int64              `json:"poll_run_id"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
	LighthouseName string             `json:"lighthouse_name"`
	Command        string             `json:"command"`
	Success        bool               `json:"success"`
	DurationMs     int64              `json:"duration_ms"`
	Output         string             `json:"output"`
	Error          pgtype.Text        `json:"error"`
}

func (q *Queries) InsertRawCommandPayload(ctx context.Context, arg InsertRawCommandPayloadParams) error {
	_, err := q.db.Exec(ctx, insertRawCommandPayload,
		arg.PollRunID,
		arg.ObservedAt,
		arg.LighthouseName,
		arg.Command,
		arg.Success,
		arg.DurationMs,
		arg.Output,
		arg.Error,
	)
	return err
}

const insertRelaySnapshot = `-- name: InsertRelaySnapshot :exec
INSERT INTO relay_snapshots (
    poll_run_id,
    observed_at,
    lighthouse_name,
    relays
) VALUES (
    $1, $2, $3, $4
)
`

type InsertRelaySnapshotParams struct {
	PollRunID      int64              `json:"poll_run_id"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
	LighthouseName string             `json:"lighthouse_name"`
	Relays         []byte             `json:"relays"`
}

func (q *Queries) InsertRelaySnapshot(ctx context.Context, arg InsertRelaySnapshotParams) error {
	_, err := q.db.Exec(ctx, insertRelaySnapshot,
		arg.PollRunID,
		arg.ObservedAt,
		arg.LighthouseName,
		arg.Relays,
	)
	return err
}

const listPresentHostmapPeers = `-- name: ListPresentHostmapPeers :many
WITH latest_poll AS (
    SELECT DISTINCT ON (lighthouse_name)
        id,
        lighthouse_name,
        started_at,
        nebula_version
    FROM poll_runs
    WHERE success
    ORDER BY lighthouse_name, started_at DESC, id DESC
),
ranked AS (
    SELECT
        h.observed_at,
        h.lighthouse_name,
        COALESCE(h.cert_fingerprint, h.primary_vpn_addr, h.local_index::text || ':' || h.remote_index::text)::text AS peer_key,
        h.primary_vpn_addr,
        h.vpn_addrs,
        h.cert_name,
        h.cert_fingerprint,
        h.cert_groups,
        p.nebula_version,
        row_number() OVER (
            PARTITION BY COALESCE(h.cert_fingerprint, h.primary_vpn_addr, h.local_index::text || ':' || h.remote_index::text)
            ORDER BY h.observed_at DESC, h.lighthouse_name, h.entry_index
        ) AS row_rank
    FROM latest_poll p
    JOIN hostmap_entries h ON h.poll_run_id = p.id
    WHERE h.source = 'hostmap'
      AND h.primary_vpn_addr IS NOT NULL
      AND h.primary_vpn_addr <> ''
)
SELECT
    observed_at,
    lighthouse_name,
    peer_key,
    primary_vpn_addr,
    vpn_addrs,
    cert_name,
    cert_fingerprint,
    cert_groups,
    nebula_version
FROM ranked
WHERE row_rank = 1
ORDER BY COALESCE(cert_name, primary_vpn_addr), primary_vpn_addr
`

type ListPresentHostmapPeersRow struct {
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	LighthouseName  string             `json:"lighthouse_name"`
	PeerKey         string             `json:"peer_key"`
	PrimaryVpnAddr  pgtype.Text        `json:"primary_vpn_addr"`
	VpnAddrs        []string           `json:"vpn_addrs"`
	CertName        pgtype.Text        `json:"cert_name"`
	CertFingerprint pgtype.Text        `json:"cert_fingerprint"`
	CertGroups      []string           `json:"cert_groups"`
	NebulaVersion   pgtype.Text        `json:"nebula_version"`
}

func (q *Queries) ListPresentHostmapPeers(ctx context.Context) ([]ListPresentHostmapPeersRow, error) {
	rows, err := q.db.Query(ctx, listPresentHostmapPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPresentHostmapPeersRow
	for rows.Next() {
		var i ListPresentHostmapPeersRow
		if err := rows.Scan(
			&i.ObservedAt,
			&i.LighthouseName,
			&i.PeerKey,
			&i.PrimaryVpnAddr,
			&i.VpnAddrs,
			&i.CertName,
			&i.CertFingerprint,
			&i.CertGroups,
			&i.NebulaVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
