// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CompletePollRun(ctx context.Context, arg CompletePollRunParams) error
	CreatePollRun(ctx context.Context, arg CreatePollRunParams) (int64, error)
	InsertHostmapEntry(ctx context.Context, arg InsertHostmapEntryParams) error
	InsertLighthouseAddrmapEntry(ctx context.Context, arg InsertLighthouseAddrmapEntryParams) error
	InsertRawCommandPayload(ctx context.Context, arg InsertRawCommandPayloadParams) error
	InsertRelaySnapshot(ctx context.Context, arg InsertRelaySnapshotParams) error
}

var _ Querier = (*Queries)(nil)
